version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    links:
      - database:postgres
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "DB_DATABASE=tictactoe"
      - "DB_USERNAME=tictactoe"
      - "DB_PASSWORD=tictactoe"

  #composer
  composer:
    image: composer/composer
    command: install
    volumes:
      - ./:/app

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # postgres
  database:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=tictactoe
      - POSTGRES_PASSWORD=tictactoe
      - POSTGRES_DB=tictactoe
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata

